# Generated by Django 5.2.1 on 2025-05-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("CSC", "Computer Science"),
                            ("NET", "Networking"),
                            ("COM", "Communications"),
                        ],
                        max_length=3,
                    ),
                ),
                ("room", models.CharField(max_length=10)),
                ("instructor", models.CharField(max_length=50)),
                ("time", models.CharField(max_length=20)),
                ("book_isbn", models.CharField(max_length=20)),
                ("book_title", models.CharField(max_length=200)),
                (
                    "prerequisite",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
        ),
    ]
